### ISSUE TITLE
CVPR 2019 Supplementary Material

### ISSUE THREAD

**Issue by Wangyouai** [AmosZhu/CVPR2019#1]
Hello, Dr. Zhu. 
  
  Thank you very much for your excellent work in open source. I recently used kinect v2 and FLIR polarizing cameras to get data and test your dem.  It turns out that the result is not as ideal as the paper, and I observe that the polarization image data provided by you is more accurate.  Therefore, I would like to ask you the following experimental questions:  
1. What kind of experimental equipment or operation can ensure the accuracy of polarization information collection?  
2. What material or spray paint do you use as the surface reflective material of the object. 
3. Which light source device do you use as a point light source?  At the same time, does the environment need absolute light isolation? 
4. Can you provide more of your test data? 

If you are free, please help me.

Greetings. 
Wang Ya.

**Comment by im-peanut** [comment]
May I ask if your issue has been resolved. bro
