### ISSUE TITLE
some questions about getting gradient form coarse depth map

### ISSUE THREAD

**Issue by Chumumu** [AmosZhu/CVPR2019#2]
Hello, I followed the process in the paper and first obtained a rough depth map with a binocular camera, but I have doubts about the step from rough depth map to guiding surface normal. The python code in this part of normal correction is to directly take the guide surface normal as input, and I am not very clear how to flush the rough depth map to solve the normal, I have two ideas (1) according to the orthogonal projection model, use a simple forward difference to find the gradient and then find the normal, (2) or according to the transmission projection model to find the gradient and normal? Looking forward to your answer, thank you

**Comment by AmosZhu** [comment]
The normal from the polarisation has ambiguity and use the depth to corrrect them. That's not compute the normal from the depth map.

**Comment by Chumumu** [comment]
Thank you very much for taking the time out of your busy schedule to answer me, but I still have doubts, the NormalCorrection block is loaded with 'N_guide' ——surface guide normals, and the later higher-order graph model uses 'N_guide' to disambiguate the normals obtained by polariza
<img width="793" alt="截屏2022-11-06 15 25 29" src="https://user-images.githubusercontent.com/72724846/200159452-f2ed8ed3-6712-4b82-bf7f-4d98512fd042.png">
tion.

**Comment by Chumumu** [comment]
Sorry, it was my negligence ,a friend just told me that the depth2normal_perspective function in the CoordinateUtil script under the NormalCorrection project can solve above doubts.
